### ISSUE TITLE
获取飞书表格数据报错

### ISSUE THREAD

**Issue by zqjy** [larksuite/oapi-sdk-python#20]
执行 .set_range("XXXX!A1:C10") 的时候报错。报错内容：AttributeError: '_SpecialForm' object has no attribute '__args__'

**Comment by zqjy** [comment]
代码：
from larksuiteoapi.api import Config, DOMAIN_FEISHU
from larksuiteoapi.service.sheets.v2 import Service

response = (
        Service(
            Config(
                DOMAIN_FEISHU,
                Config.new_internal_app_settings(
                    app_id="cli_xxx",
                    app_secret="xxx",
                ),
            )
        )
        .spreadsheetss.values_get(user_access_token=_token)
        .set_spreadsheetToken("xxx")
        .set_range("xxx!A1:C10")
        .do()
    )

报错如下：
Traceback (most recent call last):
  File "/PycharmProjects/pythonProject/lark_sheets.py", line 35, in <module>
    .set_range("Q323id!A1:C10")
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/larksuiteoapi/service/sheets/v2/api.py", line 1487, in do
    resp = req.do(conf)
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/larksuiteoapi/api/request/request.py", line 175, in do
    return Handlers(conf, self).handle()
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/larksuiteoapi/api/request/request.py", line 331, in handle
    raise e
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/larksuiteoapi/api/request/request.py", line 326, in handle
    self.send()
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/larksuiteoapi/api/request/request.py", line 253, in send
    self.parse_response()
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/larksuiteoapi/api/request/request.py", line 301, in parse_response
    resp.data = make_datatype(self.req.output_class, resp_json.get('data'))
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/larksuiteoapi/utils/dt.py", line 95, in make_datatype
    d[att_name] = make_datatype(att.type, att_value)
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/larksuiteoapi/utils/dt.py", line 95, in make_datatype
    d[att_name] = make_datatype(att.type, att_value)
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/larksuiteoapi/utils/dt.py", line 82, in make_datatype
    return [make_datatype(t.__args__[0], i) for i in kwargs]
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/larksuiteoapi/utils/dt.py", line 82, in <listcomp>
    return [make_datatype(t.__args__[0], i) for i in kwargs]
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/larksuiteoapi/utils/dt.py", line 82, in make_datatype
    return [make_datatype(t.__args__[0], i) for i in kwargs]
  File "/anaconda3/envs/py37/lib/python3.7/site-packages/larksuiteoapi/utils/dt.py", line 82, in <listcomp>
    return [make_datatype(t.__args__[0], i) for i in kwargs]
AttributeError: '_SpecialForm' object has no attribute '__args__'

**Comment by zqjy** [comment]
查看了源码之后发现请求成功了但是解析respone的时候出问题了因为values_get会返回一个list

**Comment by Lips7** [comment]
有同样的问题😭，辛苦开发者帮忙看一下，sheet api 里 values_get后返回list，没法直接类型推断，list对象没有`__args__`属性，只有list[str]才会有，这里可能需要捕获一下异常直接退出然后返回原始的数据类型

**Comment by zhaoche27** [comment]
好的，谢谢你的返回，给提供反馈的json数据吗，伪数据就行，结构对的就行，数据是假的，我来测试一下， utils/dt.py

**Comment by zhaoche27** [comment]
{
        "revision": 0,
        "spreadsheetToken": "***",
        "valueRange": {
            "majorDimension": "ROWS",
            "range": "***",
            "revision": 0,
            "values": [
                [
                    "***"
                ]
            ]
        }
    }


values 是一个 二维数组，是吧？

**Comment by Lips7** [comment]
> { "revision": 0, "spreadsheetToken": "_**", "valueRange": { "majorDimension": "ROWS", "range": "**_", "revision": 0, "values": [ [ "***" ] ] } }
> 
> values 是一个 二维数组，是吧？

是的

**Comment by zhaoche27** [comment]
pip install larksuite-oapi==1.0.32 @Lips7
