### ISSUE TITLE
Transport cannot deal with utf-8 request body

### ISSUE THREAD

**Issue by harborbor** [larksuite/oapi-sdk-python#44]
D:\repos\oapi-sdk-python> & C:/Users/xm/AppData/Local/Programs/Python/Python310/python.exe d:/repos/oapi-sdk-python/test.py
[Lark] [2023-07-26 11:57:45,031] [DEBUG] POST https://xxxxx//open-apis/auth/v3/tenant_access_token/internal 200, headers: {"User-Agent": "oapi-sdk-python/v1.0.0"}, params: [], body: {"app_id": "xxx", "app_secret": "xxx", "app_ticket": null, "app_access_token": null, "tenant_key": null}
Traceback (most recent call last):
  File "d:\repos\oapi-sdk-python\test.py", line 64, in <module>
    test_create_record({"ReleaseLink":{"text":'sss',"link":'www.baidu.com'},"发布日期":datetime.datetime.now().astimezone().isoformat(),"Changelog":'aaaa',"描述":'tagMsg',"发布版本":'tagThis',"项目 
配置":'ssss'},"tbllCztYEz7Drn4A")
  File "d:\repos\oapi-sdk-python\test.py", line 51, in test_create_record
    response: CreateAppTableRecordResponse = client.bitable.v1.app_table_record.create(request)    
  File "d:\repos\oapi-sdk-python\lark_oapi\api\bitable\v1\resource\app_table_record.py", line 95, in create
    resp: RawResponse = Transport.execute(self.config, request, option)
  File "d:\repos\oapi-sdk-python\lark_oapi\core\http\transport.py", line 26, in execute
    response = requests.request(
  File "C:\Users\xm\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\xm\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\xm\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\xm\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\xm\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\xm\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\xm\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\xm\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\xm\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1327, in _send_request
    body = _encode(body, 'body')
  File "C:\Users\xm\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 166, in _encode
    raise UnicodeEncodeError(
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 185-188: Body ('发布日期') 
is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

**Comment by maowenbo666** [comment]
Solved in latest version.
